spring.application.name=Online_Elections
server.port = ${PORT:8081}
spring.application.debug = true
server.address = 0.0.0.0

# databse connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${DB_PASSWORD}

# hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE